site_name: Leto2Bot
repo_url: https://github.com/masaiio
pages:
- Home: index.md
- About: about.md
- Guides:
    - Install Guide: guides/Windows Guide.md
- Commands:
    - Readme: Readme.md
    - Commands List: Commands List.md
- Features Explained:
    - JSON Explanations: JSON Explanations.md
    - Permissions System: Permissions System.md
    - Custom Reactions: Custom Reactions.md
    - Placeholders: Placeholders.md
- Frequently Asked Questions: Frequently Asked Questions.md
- Contribution Guide: Contribution Guide.md
- ❤ Donate ❤: Donate.md

theme: readthedocs
